version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30001:80"
    healthcheck:
      test: curl -f http://localhost:80 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
